site_name: CleanQRL Documentation
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: blue

plugins:
   - search
   - awesome-nav

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/georgkruse/cleanqrl
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rodrigo-coelho140/  
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/georg-kruse-71494517a/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/georgkruse/cleanqrl?tab=License-1-ov-file"  target="_blank" rel="noopener">CleanQRL</a>